### PR TITLE
Reworking aside logo section to use img tag so it's easier to include…

### PR DESCRIPTION
**Pull request by goranradmanovic**
@vgkids Please check this new PR for reworking logo section to use inmg tag instead of bg. image so it's easier to include logo from another company

### CODE REVIEW

**Review by drowninginflowers — CHANGES_REQUESTED** [review]
Better, but still not quite right. You can see in the attached image that it's still not scaling an example logo correctly.

Here's how a logo displays right now.
image

It should look something like this instead.
correct logo display

Generally, since logos will have different shapes, it should scale so that all edges fit inside the display area without changing the aspect ratio

**Comment by vgkids** [comment]
In @drowninginflowers 's example the entire logo is showing, which is good, but it should have some padding around it as well. It should be similar to the 'arrows-only' trivial version, since a circle logo uses the same image for both.

**Comment by goranradmanovic** [comment]
@vgkids @drowninginflowers Please check now this PR with different image sizes
1000x1000
600x400

**Comment by vgkids** [comment]
@goranradmanovic The image is no longer cropping and we're maintaining the aspect ratio like we should, but it's much too large (this branch, shown right). It needs max width and height properties to be the same height as the trivial logo, so it looks like the image on the left. 
Screenshot 2024-08-02 at 10 03 21 AM

**Review by drowninginflowers — APPROVED** [review]
Looks all good now!

full width sidebar
image

sidebar minimized
image

**Pull request merged**
