### PR TITLE
Finishing with mobile responsivnes for all new pages done with PrimeVue lib.

### PR DESCRIPTION
**Pull request by goranradmanovic**
@vgkids Please check this new PR for mobile respons.

### CODE REVIEW

**Comment by vgkids** [comment]
@goranradmanovic Can you resolve the conflicts here or copy the changes into a fresh branch from main? Changes look OK otherwise.

**Comment by goranradmanovic** [comment]
> @goranradmanovic Can you resolve the conflicts here or copy the changes into a fresh branch from main? Changes look OK otherwise.

@vgkids I have fix merge conflict on this branch

**Comment by goranradmanovic** [comment]
@vgkids Please check now this PR

**Review by vgkids — APPROVED** [review]
Looks great, thank you.

**Pull request merged**
